import {
    Program, Stmt, Expr, VarDeclaration, FunctionDeclaration, IfStatement,
    WhileStatement, LoopStatement, ForEachStatement, ForStatement,
    MatchStatement, TryCatchStatement, SayStatement, FlexStatement,
    PushStatement, PopStatement, NamespaceDeclaration, ImportStatement,
    SquadDeclaration, ExpressionStatement, BinaryExpr, AssignmentExpr,
    CallExpr, MemberExpr, Identifier, NumericLiteral, StringLiteral,
    BooleanLiteral, ArrayLiteral, ObjectLiteral, StashExpr, SizeExpr,
    TypeExpr, PopExpr, PanicExpr, AwaitExpr, AskExpr, ReturnStatement,
    JsBlock, NaturalCommandStmt, FetchExpr
} from "./ast";

export class Transpiler {
    private indentLevel = 0;

    transpile(program: Program): string {
        let out = `/**
 * Generated by Vybe Compiler
 */
const readlineSync = require("readline-sync");

const __vybe_runtime = {
    getPrintable: (val) => {
        if (typeof val === "string") return val;
        if (typeof val === "number") return val.toString();
        if (typeof val === "boolean") return val ? "frfr" : "cap";
        if (val === null || val === undefined) return "ghost";
        if (Array.isArray(val)) return "[" + val.map(__vybe_runtime.getPrintable).join(", ") + "]";
        if (typeof val === "object") {
            const keys = Object.keys(val);
            return "{ " + keys.map(k => k + ": " + __vybe_runtime.getPrintable(val[k])).join(", ") + " }";
        }
        return String(val);
    },
    say: (v) => console.log(__vybe_runtime.getPrintable(v)),
    ask: (p) => readlineSync.question(p),
    flex: (v) => console.dir(v, { depth: null }),
    size: (v) => {
        if (Array.isArray(v)) return v.length;
        if (typeof v === "string") return v.length;
        if (typeof v === "object" && v !== null) return Object.keys(v).length;
        return 0;
    },
    type: (v) => {
        if (Array.isArray(v)) return "list";
        return typeof v;
    },
    crash: (m) => { console.error(m); process.exit(1); },
    fetch: async (url) => {
        const res = await fetch(url);
        return await res.json();
    }
};

async function main() {
    try {
`;
        this.indentLevel++;
        out += program.body.map(stmt => this.transpileStmt(stmt)).join("\n");
        this.indentLevel--;
        out += `
    } catch (err) {
        console.error("[Runtime Error]", err);
        process.exit(1);
    }
}

main().catch(err => {
    console.error("[Fatal Error]", err);
    process.exit(1);
});
`;
        return out;
    }

    private indent(): string {
        return "  ".repeat(this.indentLevel);
    }

    private transpileStmt(stmt: Stmt): string {
        switch (stmt.kind) {
            case "VarDeclaration":
                return this.transpileVarDeclaration(stmt as VarDeclaration);
            case "FunctionDeclaration":
                return this.transpileFunctionDeclaration(stmt as FunctionDeclaration);
            case "IfStatement":
                return this.transpileIfStatement(stmt as IfStatement);
            case "WhileStatement":
                return this.transpileWhileStatement(stmt as WhileStatement);
            case "LoopStatement":
                return this.transpileLoopStatement(stmt as LoopStatement);
            case "ForEachStatement":
                return this.transpileForEachStatement(stmt as ForEachStatement);
            case "ForStatement":
                return this.transpileForStatement(stmt as ForStatement);
            case "MatchStatement":
                return this.transpileMatchStatement(stmt as MatchStatement);
            case "TryCatchStatement":
                return this.transpileTryCatchStatement(stmt as TryCatchStatement);
            case "SayStatement":
                return this.transpileSayStatement(stmt as SayStatement);
            case "FlexStatement":
                return this.transpileFlexStatement(stmt as FlexStatement);
            case "JsBlock":
                return this.transpileJsBlock(stmt as JsBlock);
            case "NaturalCommandStmt":
                return this.transpileNaturalCommandStmt(stmt as NaturalCommandStmt);
            case "PushStatement":
                return this.transpilePushStatement(stmt as PushStatement);
            case "PopStatement":
                return this.transpilePopStatement(stmt as PopStatement);
            case "ReturnStatement":
                return this.transpileReturnStatement(stmt as ReturnStatement);
            case "BreakStatement":
                return this.indent() + "break;";
            case "ContinueStatement":
                return this.indent() + "continue;";
            case "NamespaceDeclaration":
                return this.transpileNamespaceDeclaration(stmt as NamespaceDeclaration);
            case "SquadDeclaration":
                return this.transpileSquadDeclaration(stmt as SquadDeclaration);
            case "ExpressionStatement":
                return this.transpileExpressionStatement(stmt as ExpressionStatement);
            default:
                return `${this.indent()}// Skip ${stmt.kind}`;
        }
    }

    private transpileVarDeclaration(stmt: VarDeclaration): string {
        return `${this.indent()}let ${stmt.identifier} = ${this.transpileExpr(stmt.value)};`;
    }

    private transpileFunctionDeclaration(stmt: FunctionDeclaration): string {
        const asyncToken = stmt.isAsync ? "async " : "";
        const name = stmt.name === "anonymous" ? "" : stmt.name;
        const params = stmt.parameters.join(", ");

        if (stmt.isArrow) {
            const bodyExpr = (stmt.body.body[0] as any).argument;
            return `${this.indent()}const ${name} = ${asyncToken}(${params}) => ${this.transpileExpr(bodyExpr)};`;
        }

        let out = `${this.indent()}${asyncToken}function ${name}(${params}) {\n`;
        this.indentLevel++;
        out += stmt.body.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;
        return out;
    }

    private transpileIfStatement(stmt: IfStatement): string {
        let out = `${this.indent()}if (${this.transpileExpr(stmt.condition)}) {\n`;
        this.indentLevel++;
        out += stmt.thenBranch.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;

        for (const branch of stmt.elseIfBranches) {
            out += ` else if (${this.transpileExpr(branch.condition)}) {\n`;
            this.indentLevel++;
            out += branch.consequent.body.map(s => this.transpileStmt(s)).join("\n");
            this.indentLevel--;
            out += `\n${this.indent()}}`;
        }

        if (stmt.elseBranch) {
            out += ` else {\n`;
            this.indentLevel++;
            out += stmt.elseBranch.body.map(s => this.transpileStmt(s)).join("\n");
            this.indentLevel--;
            out += `\n${this.indent()}}`;
        }
        return out;
    }

    private transpileWhileStatement(stmt: WhileStatement): string {
        let out = `${this.indent()}while (${this.transpileExpr(stmt.condition)}) {\n`;
        this.indentLevel++;
        out += stmt.body.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;
        return out;
    }

    private transpileLoopStatement(stmt: LoopStatement): string {
        const i = `__i${Math.floor(Math.random() * 1000)}`;
        let out = `${this.indent()}for(let ${i} = 0; ${i} < ${this.transpileExpr(stmt.count)}; ${i}++) {\n`;
        this.indentLevel++;
        out += stmt.body.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;
        return out;
    }

    private transpileForStatement(stmt: ForStatement): string {
        let out = `${this.indent()}for(let ${stmt.init} = ${this.transpileExpr(stmt.start)}; ${stmt.init} <= ${this.transpileExpr(stmt.end)}; ${stmt.init}++) {\n`;
        this.indentLevel++;
        out += stmt.body.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;
        return out;
    }

    private transpileForEachStatement(stmt: ForEachStatement): string {
        let out = `${this.indent()}for(const ${stmt.item} of ${this.transpileExpr(stmt.list)}) {\n`;
        this.indentLevel++;
        out += stmt.body.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;
        return out;
    }

    private transpileMatchStatement(stmt: MatchStatement): string {
        const arg = `__match${Math.floor(Math.random() * 1000)}`;
        let out = `${this.indent()}const ${arg} = ${this.transpileExpr(stmt.argument)};\n`;
        out += `${this.indent()}switch(true) {\n`;
        this.indentLevel++;
        for (const c of stmt.cases) {
            if (c.isDefault) {
                out += `${this.indent()}default:\n`;
            } else {
                out += `${this.indent()}case (${arg} === ${this.transpileExpr(c.condition)}):\n`;
            }
            this.indentLevel++;
            out += c.body.body.map(s => this.transpileStmt(s)).join("\n");
            out += `\n${this.indent()}break;\n`;
            this.indentLevel--;
        }
        this.indentLevel--;
        out += `${this.indent()}}`;
        return out;
    }

    private transpileTryCatchStatement(stmt: TryCatchStatement): string {
        let out = `${this.indent()}try {\n`;
        this.indentLevel++;
        out += stmt.tryBlock.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}} catch (${stmt.catchIdentifier}) {\n`;
        this.indentLevel++;
        out += stmt.catchBlock.body.map(s => this.transpileStmt(s)).join("\n");
        this.indentLevel--;
        out += `\n${this.indent()}}`;
        return out;
    }

    private transpileSayStatement(stmt: SayStatement): string {
        return `${this.indent()}__vybe_runtime.say(${this.transpileExpr(stmt.argument)});`;
    }

    private transpileJsBlock(stmt: JsBlock): string {
        return `${this.indent()}${stmt.code}`;
    }

    private transpileNaturalCommandStmt(stmt: NaturalCommandStmt): string {
        const verb = stmt.verb;
        const arg = this.transpileExpr(stmt.argument);
        const dest = stmt.destination ? this.transpileExpr(stmt.destination) : null;

        switch (verb) {
            case "wait":
                return `${this.indent()}await new Promise(r => setTimeout(r, ${arg} * 1000));`;
            case "fetch":
                return dest
                    ? `${this.indent()}${dest} = await __vybe_runtime.fetch(${arg});`
                    : `${this.indent()}await __vybe_runtime.fetch(${arg});`;
            default:
                return `${this.indent()}// Todo: Natural Command ${verb}`;
        }
    }

    private transpileFlexStatement(stmt: FlexStatement): string {
        return `${this.indent()}__vybe_runtime.flex(${this.transpileExpr(stmt.argument)});`;
    }

    private transpilePushStatement(stmt: PushStatement): string {
        return `${this.indent()}${this.transpileExpr(stmt.list)}.push(${this.transpileExpr(stmt.value)});`;
    }

    private transpilePopStatement(stmt: PopStatement): string {
        return `${this.indent()}${this.transpileExpr(stmt.list)}.pop();`;
    }

    private transpileReturnStatement(stmt: ReturnStatement): string {
        return `${this.indent()}return ${stmt.argument ? this.transpileExpr(stmt.argument) : "null"};`;
    }

    private transpileNamespaceDeclaration(stmt: NamespaceDeclaration): string {
        let out = `${this.indent()}const ${stmt.name} = (() => {\n`;
        this.indentLevel++;
        const exportedVars: string[] = [];
        // This is a bit complex as we need to know what to export. 
        // For simplicity, we'll just put everything in a literal return at the end.
        out += stmt.body.map(s => {
            if (s.kind === "VarDeclaration") exportedVars.push((s as VarDeclaration).identifier);
            if (s.kind === "FunctionDeclaration") exportedVars.push((s as FunctionDeclaration).name);
            return this.transpileStmt(s);
        }).join("\n");
        out += `\n${this.indent()}return { ${exportedVars.join(", ")} };\n`;
        this.indentLevel--;
        out += `${this.indent()}})();`;
        return out;
    }

    private transpileSquadDeclaration(stmt: SquadDeclaration): string {
        let out = `${this.indent()}class ${stmt.name} {\n`;
        this.indentLevel++;
        for (const method of stmt.methods) {
            const name = method.name === "init" ? "constructor" : method.name;
            const asyncToken = method.isAsync ? "async " : "";
            out += `${this.indent()}${asyncToken}${name}(${method.parameters.join(", ")}) {\n`;
            this.indentLevel++;
            out += method.body.body.map(s => this.transpileStmt(s)).join("\n");
            this.indentLevel--;
            out += `\n${this.indent()}}\n`;
        }
        this.indentLevel--;
        out += `${this.indent()}}`;
        return out;
    }

    private transpileExpressionStatement(stmt: ExpressionStatement): string {
        return `${this.indent()}${this.transpileExpr(stmt.expression)};`;
    }

    private transpileExpr(expr: Expr): string {
        switch (expr.kind) {
            case "BinaryExpr":
                const binary = expr as BinaryExpr;
                return `(${this.transpileExpr(binary.left)} ${binary.operator} ${this.transpileExpr(binary.right)})`;
            case "AssignmentExpr":
                const assign = expr as AssignmentExpr;
                return `${this.transpileExpr(assign.assignee)} = ${this.transpileExpr(assign.value)}`;
            case "CallExpr":
                const call = expr as CallExpr;
                return `(await ${this.transpileExpr(call.caller)}(${call.args.map(a => this.transpileExpr(a)).join(", ")}))`;
            case "MemberExpr":
                const member = expr as MemberExpr;
                if (!member.computed && member.property.kind === "Identifier") {
                    const prop = (member.property as Identifier).symbol;
                    if (prop === "size" || prop === "len") {
                        return `__vybe_runtime.size(${this.transpileExpr(member.object)})`;
                    }
                }
                const propAccess = member.computed ? `[${this.transpileExpr(member.property)}]` : `.${this.transpileExpr(member.property)}`;
                return `${this.transpileExpr(member.object)}${propAccess}`;
            case "Identifier":
                const id = (expr as Identifier).symbol;
                if (id === "frfr" || id === "fr") return "true";
                if (id === "cap") return "false";
                return id;
            case "NumericLiteral":
                return (expr as NumericLiteral).value.toString();
            case "StringLiteral":
                return `"${(expr as StringLiteral).value}"`;
            case "BooleanLiteral":
                return (expr as BooleanLiteral).value ? "true" : "false";
            case "ArrayLiteral":
                return `[${(expr as ArrayLiteral).elements.map(e => this.transpileExpr(e)).join(", ")}]`;
            case "ObjectLiteral":
                const obj = expr as ObjectLiteral;
                return `{ ${obj.properties.map(p => this.transpileProperty(p)).join(", ")} }`;
            case "StashExpr":
                return `${this.transpileExpr((expr as StashExpr).elements[0])}`;
            case "SizeExpr":
                return `__vybe_runtime.size(${this.transpileExpr((expr as SizeExpr).argument)})`;
            case "TypeExpr":
                return `__vybe_runtime.type(${this.transpileExpr((expr as TypeExpr).argument)})`;
            case "PopExpr":
                return `${this.transpileExpr((expr as PopExpr).list)}.pop()`;
            case "PanicExpr":
                return `__vybe_runtime.crash(${this.transpileExpr((expr as PanicExpr).argument)})`;
            case "AwaitExpr":
                return `(await ${this.transpileExpr((expr as AwaitExpr).argument)})`;
            case "AskExpr":
                return `(await __vybe_runtime.ask(${this.transpileExpr((expr as AskExpr).message)}))`;
            case "FetchExpr":
                return `(await __vybe_runtime.fetch(${this.transpileExpr((expr as FetchExpr).url)}))`;
            default:
                return `null /* Unknown ${expr.kind} */`;
        }
    }

    private transpileProperty(prop: any): string {
        if (!prop.value) return prop.key;
        return `${prop.key}: ${this.transpileExpr(prop.value)}`;
    }
}
